export enum EProvider {
  LINKED_IN = "LINKED_IN",
  GREENHOUSE = "GREENHOUSE",
  INDEED = "INDEED",
  SEEK = "SEEK",
  WORKDAY = "WORKDAY",
  LEVER = "LEVER",
  JOB_VISION = "JOB_VISION",
  IRAN_TALENT = "IRAN_TALENT",
  JOB_IN_JA = "JOB_IN_JA",
}
