name: CD

on:
  workflow_run:
    workflows:
      - Release
    types: completed
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }} \
            .

      - name: Push docker image
        run: |
          docker push \
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
