name: CI

on:
  push:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Generate prisma client
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.CI_DATABASE_URL }}

      - name: Check types
        run: npm run typecheck
